// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI22G7s9s3oKaof8XQc--28fdjPDBf7IA',
    appId: '1:789149704986:web:5d17f431022aeb944d42a3',
    messagingSenderId: '789149704986',
    projectId: 'maketon',
    authDomain: 'maketon.firebaseapp.com',
    storageBucket: 'maketon.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHm6Gvg_QqpoDG1n4dXg9Ju60odVtyGyE',
    appId: '1:789149704986:android:ce7aa9999929b6a94d42a3',
    messagingSenderId: '789149704986',
    projectId: 'maketon',
    storageBucket: 'maketon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3A3X21CC93w6wQICRIoNTS2riftepRZE',
    appId: '1:789149704986:ios:e52e7347c0b9ec2e4d42a3',
    messagingSenderId: '789149704986',
    projectId: 'maketon',
    storageBucket: 'maketon.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3A3X21CC93w6wQICRIoNTS2riftepRZE',
    appId: '1:789149704986:ios:e52e7347c0b9ec2e4d42a3',
    messagingSenderId: '789149704986',
    projectId: 'maketon',
    storageBucket: 'maketon.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAI22G7s9s3oKaof8XQc--28fdjPDBf7IA',
    appId: '1:789149704986:web:8a86ec1916181d614d42a3',
    messagingSenderId: '789149704986',
    projectId: 'maketon',
    authDomain: 'maketon.firebaseapp.com',
    storageBucket: 'maketon.firebasestorage.app',
  );
}
