// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgbjAErjGVu3p3iPbsR5BfLnaaFKHLL8k',
    appId: '1:294673548071:web:e97e2f2479775b80569f02',
    messagingSenderId: '294673548071',
    projectId: 'maketonnn',
    authDomain: 'maketonnn.firebaseapp.com',
    storageBucket: 'maketonnn.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC8UDS2HNoBOSoBWrJFXnZTSCRQNIE1y8',
    appId: '1:294673548071:android:4a4d2671a77bd177569f02',
    messagingSenderId: '294673548071',
    projectId: 'maketonnn',
    storageBucket: 'maketonnn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdcRkJfN0s2uMCxs7zy6XKTu8ccibW2kg',
    appId: '1:294673548071:ios:3436e94fc2e67d16569f02',
    messagingSenderId: '294673548071',
    projectId: 'maketonnn',
    storageBucket: 'maketonnn.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdcRkJfN0s2uMCxs7zy6XKTu8ccibW2kg',
    appId: '1:294673548071:ios:3436e94fc2e67d16569f02',
    messagingSenderId: '294673548071',
    projectId: 'maketonnn',
    storageBucket: 'maketonnn.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgbjAErjGVu3p3iPbsR5BfLnaaFKHLL8k',
    appId: '1:294673548071:web:df0a09e398a0d401569f02',
    messagingSenderId: '294673548071',
    projectId: 'maketonnn',
    authDomain: 'maketonnn.firebaseapp.com',
    storageBucket: 'maketonnn.firebasestorage.app',
  );
}
